# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/pry-byebug/all/pry-byebug.rbi
#
# pry-byebug-3.6.0
module PryByebug
  def check_file_context(target, e = nil); end
  def current_remote_server; end
  def current_remote_server=(arg0); end
  def file_context?(target); end
  def self.check_file_context(target, e = nil); end
  def self.file_context?(target); end
end
