plugins: rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
    NewCops: enable
    SuggestExtensions: false
RSpec/DescribedClass:
  EnforcedStyle: explicit
Style/StringLiterals:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/MapIntoArray:
  Enabled: false
Layout/LineLength:
  Max: 120
